name: YouTube Live Downloader
on:
  schedule:
    - cron: '*/10 20-22 * * 5,6,0'
  workflow_dispatch:
jobs:
  download-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install yt-dlp google-auth-oauthlib google-auth-httplib2 google-api-python-client requests
      - name: Copy credentials and cookies
        run: |
          echo "${{ secrets.CREDENTIALS_JSON }}" > credentials.json
          echo "${{ secrets.TOKEN_JSON }}" > token.json
          echo "${{ secrets.COOKIES_TXT }}" > /tmp/cookies.txt
      - name: Check for live stream and download
        id: download
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          python check_live_stream.py || echo "Download failed, checking output"
          # FILENAME is set by the script using the video ID
          if [ ! -f "${{ env.FILENAME }}" ]; then
            echo "No video file found, skipping upload."
            exit 0
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: downloaded-video
          path: ${{ env.FILENAME }}
      - name: Upload to Google Drive
        if: success() && env.FILENAME != ''
        run: |
          if [ -f "${{ env.FILENAME }}" ]; then
            python upload_to_drive.py "${{ env.FILENAME }}"
          else
            echo "File ${{ env.FILENAME }} not found, relying on artifact."
            exit 0
          fi
